---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - rabbitmq_exporter_install
    - rabbitmq_exporter_configure
    - rabbitmq_exporter_run

- import_tasks: preflight.yml
  tags:
    - rabbitmq_exporter_install
    - rabbitmq_exporter_configure
    - rabbitmq_exporter_run

- import_tasks: install.yml
  become: true
# when: (not __rabbitmq_exporter_is_installed.stat.exists) or (__rabbitmq_exporter_current_version_output.stderr_lines[0].split(" ")[2] != rabbitmq_exporter_version)
  tags:
    - rabbitmq_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - rabbitmq_exporter_configure

- name: Ensure RabbitMQ Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: rabbitmq_exporter
    enabled: true
    state: started
  tags:
    - rabbitmq_exporter_run
