---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    rabbitmq_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in rabbitmq_exporter_web_listen_address"

- name: Check if rabbitmq_exporter is installed
  stat:
    path: "/usr/local/bin/rabbitmq_exporter"
  register: __rabbitmq_exporter_is_installed
  tags:
    - rabbitmq_exporter_install

- name: Gather currently installed rabbitmq_exporter version (if any)
  command: "/usr/local/bin/rabbitmq_exporter --version"
  args:
    warn: false
  changed_when: false
  register: __rabbitmq_exporter_current_version_output
  when: __rabbitmq_exporter_is_installed.stat.exists
  tags:
    - rabbitmq_exporter_install
    - skip_ansible_lint
    