---

- name: rabbitmq exporter service reenable
  command: systemctl reenable prometheus-rabbitmq-exporter.service

- name: restart rabbitmq_exporter
  become: true
  systemd:
    daemon_reload: true
    name: rabbitmq_exporter
    state: restarted